### ISSUE TITLE
PyCharm - No legend available in matrixprofile.analyze() output figures

### ISSUE THREAD

**Issue by giapippa** [matrix-profile-foundation/matrixprofile#10]
I can't see the legend in plots of the matrixprofile.analyze() function:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17180372/76093677-b4828180-5fc1-11ea-92c1-1b50dc090502.png">

I am running Python 3.7 on Mac OS with matplotlib, backend="Qt5Agg", on the console of PyCharm.

**Comment by tylerwmarrs** [comment]
@giapippa Did you try to use any other backends? This seems to be an issue very specific to your coding environment. I'm not too familiar with using PyCharm.

**Comment by giapippa** [comment]
I tried also MacOSX and TkAgg but nothing changes; I guess its a problem of PyCharm with Mac OS.

**Comment by tylerwmarrs** [comment]
@giapippa Are you able to fork and create a pull request with a fix? Given this is so specific to your environment, it will be difficult for me to recreate and debug this issue.

**Comment by vanbenschoten** [comment]
Closing this issue for now. It can be re-opened if others encounter the same problem.
