### ISSUE TITLE
New release version required to include removal of strict protobuf dependency 

### ISSUE THREAD

**Issue by PJPRoche** [matrix-profile-foundation/matrixprofile#102]
**Describe the bug**

The latest tagged release is 1.1.10 and includes a pinned version of protobuf "protobuf==3.11.2" in the setup.py https://github.com/matrix-profile-foundation/matrixprofile/blob/ffe21d4077e89ce995e21be279460c2b3613bffc/setup.py#L71

The latest version of the matrixprofile code includes a critical change https://github.com/matrix-profile-foundation/matrixprofile/commit/e05b0493f467c925f79c0c5e298ce389dacca175 that is not included in version 1.1.10

When you do a pip install, this change is not reflected and you get protobuf dependency conflicts/issues with other modules

Can you please create a new tagged release 1.1.11 so the fixed protobuf dependency issue is included

**Comment by arturdaraujo** [comment]
I fully agree! I'm also having a lot dependence issues using conda-forge

**Comment by arturdaraujo** [comment]
Any new on this issue? @vanbenschoten

**Comment by vanbenschoten** [comment]
This library is not actively maintained. Per conversations last year with tsfresh, matrixprofile can be moved to a dependency or have its functionality replaced with the stumpy library (which is already a tsfresh dependency).
