### ISSUE TITLE
Annotation Vectors

### ISSUE THREAD

**Issue by tylerwmarrs** [matrix-profile-foundation/matrixprofile#11]
Annotation vectors provide a way to "filter" a matrix profile to avoid noisy results. In essence, an annotation vector is a vector containing values ranging from 0 to 1 where 0 means "less desirable" and 1 means "very desirable". The length of the annotation vector is the same as the matrix profile and the annotation vector is applied to a matrix profile to create a "corrected matrix profile" (CMP).

**Describe the solution you'd like**
* There should be some default annotation vectors to apply.
* Where does this fit into the current model? Is it simply a utility? We could introduce a new "transform" concept.
* The annotation vector should be stored alongside the MP data structure.

Example code with new "transform" concept:
```python
import matrixprofile as mp
ts = None # load some data
w = 100 # the window size
profile = mp.compute(ts, windows=w)
av = None # some default annotation vector or user defined one
profile = mp.transform.apply_av(profile, av)

# a different idea is to just put this in as a utility function
profile = mp.utils.apply_av(profile, av)
```

The original profile data structure is returned with an additional "av" and "cmp" key in both cases.

Where would we actually store some default annotation vectors? These can be derived from a time series. For example, our Golang library has annotation vectors implemented here:

https://github.com/matrix-profile-foundation/go-matrixprofile/blob/master/av/annotation_vector.go

**Additional context**

You can find the paper describing annotation vectors here:
https://www.cs.ucr.edu/~eamonn/guided-motif-KDD17-new-format-10-pages-v005.pdf

**Comment by nikita-smyrnov** [comment]
Is there a reason as to why these annotation vectors were not implemented/reused from the previous Python library? They seem to be present in both the R and Go packages, so is this a feature that will be added in soon or will it take longer to develop?

**Comment by tylerwmarrs** [comment]
@nikita-smyrnov The original Python library was not used during the creation of this library at all. This is due to some political and technical decisions made at MPF. Some features existed in the R and Golang library prior to the MPF being established (annotation vectors being one feature). This Python library was written from the ground up introducing fundamental concepts that we feel are needed to reach a broader audience; predominantly higher-level concepts beyond algorithmic detail.

With all of this in mind, it would be beneficial to understand your use cases of annotation vectors. As mentioned earlier in this issue, annotation vectors are more or less a domain-specific statistical filter. The goal is to understand the core filters that we should offer within the library. Will you please take some time to explain your use cases?

This feature could be implemented relatively quick depending on the complexity of filters. It would be awesome if someone like yourself could contribute code. I'm the only developer of the Python library at this time.

**Comment by nikita-smyrnov** [comment]
Our use cases of annotation vectors is related to process mining (i.e. data mining and time series analysis but for business/event logs). I'm afraid I can't go too much further as some of the information in our use case may be confidential.

I'll fork the project and contribute to this repository. I'll submit a pull request when I have a finalized and unit-tested version of the annotation vector feature.

**Comment by nikita-smyrnov** [comment]
Alright, I've submitted a pull request that should be compliant with the specifications on the main website. Let me know if any other edits are needed (note that the unit tests have been cross-checked with the Go MatrixProfile library to make sure that the same results are generated across multiple MatrixProfile libraries).

**Comment by tylerwmarrs** [comment]
PR #16 resolves this issue.

**Comment by tylerwmarrs** [comment]
@nikita-smyrnov v1.1.0 is released on PyPi. See https://github.com/matrix-profile-foundation/matrixprofile/blob/master/docs/Releases.md
