### ISSUE TITLE
Multi-Dimensional Matrix Profiles

### ISSUE THREAD

**Issue by tylerwmarrs** [matrix-profile-foundation/matrixprofile#15]
**Overview**
Right now all of the algorithms implemented support one-dimensional matrix profiles. There have been a handful of requests on our discord channel asking for multi-dimensional support. This issue is used to keep track of the request and give an opportunity to the community for contributions.

**Todos**
- Data structure supporting multiple dimensions
- Motif discovery
- Discord discovery
- Figure out what algorithms should be updated. I'm guessing MPX and SCRIMP++ only?
- Update analyze and compute higher-level functions to pass off multi-dimensional time series to the right algorithm.
- Update I/O module

**Relevant papers**
[Matrix Profile VI: Meaningful Multidimensional Motif Discovery. Chin-Chia Michael Yeh, Nickolas Kavantzas, Eamonn Keogh. [pdf] ICDM 2017.](http://www.cs.ucr.edu/~eamonn/Motif_Discovery_ICDM.pdf)

Domain Agnostic Online Semantic Segmentation for Multi-Dimensional Time Series. Shaghayegh Gharghabi, Chin-Chia Michael Yeh, Yifei Ding, Wei Ding, Paul Hibbing, Samuel LaMunion, Andrew Kaplan, Scott E. Crouter, Eamonn Keogh. Data Mining and Knowledge Discovery.

**Comment by asuhag** [comment]
I would like to help out. Where and how can I start?

**Comment by vanbenschoten** [comment]
@asuhag apologies! I just saw your message now (not sure why GitHub didn't alert me). Are you still interested in helping out?

**Comment by vanbenschoten** [comment]
I'm starting to dig into this one (the paper, anyway). Here's a link to Yeh's original mstamp code in Python: https://github.com/mcyeh/mstamp/tree/master/Python

**Comment by vanbenschoten** [comment]
We'll see how far I can get on the implementation.

**Comment by Sandy4321** [comment]
when will be ready?

**Comment by RexKing6** [comment]
Hey, I have successfully completed my thesis. Now I have part of my time to help out. How can I start?

**Comment by vanbenschoten** [comment]
@RexKing6 Congratulations! In terms of next steps, the next thing would be to review Yeh's original MSTAMP implementation (see above) and see if it can be directly leveraged in the matrixprofile package. I think we can focus on implementing MSTAMP at first, so feel free to open a PR and we can all collaborate on it (@asuhag had also mentioned interested).

**Comment by RexKing6** [comment]
OK.

**Comment by RexKing6** [comment]
Hi, @vanbenschoten , I added mstomp (mstamp based on stomp) and its some test and created the the pull request. Moreover, I updated some annotations.

**Comment by RexKing6** [comment]
Oh, I found that I encountered two alerts, and the code that caused the two alerts is from  stomp.py. Should I modify them?

**Comment by vanbenschoten** [comment]
The code or the alerts? Ideally the former :)

**Comment by RexKing6** [comment]
The code: 
`            start = batch_windows[index][0]
            end = batch_windows[index][1]`
In the multi-thread loop, these two variables are not used. :)

**Comment by vanbenschoten** [comment]
@RexKing6 after taking a look, I'm not worried by the warning, so I'll go ahead and merge. Thanks so much for the commit!! Really appreciate your work.
