### ISSUE TITLE
Where is a good place to ask questions about the library and general place for help on debugging matrix profile related code?

### ISSUE THREAD

**Issue by JulianFN** [matrix-profile-foundation/matrixprofile#18]

**Comment by tylerwmarrs** [comment]
If you have an issue specifically with this library, github is a good place to create an issue. Otherwise we have a public discord server for general questions.

See this link

https://matrixprofile.docs.matrixprofile.org/help.html

**Comment by tylerwmarrs** [comment]
I'm closing this issue as there is no bug/issue to solve. We started a conversation on Discord covering use case.
