### ISSUE TITLE
Gracefully handle zero window size, zero data

### ISSUE THREAD

**Issue by coljac** [matrix-profile-foundation/matrixprofile#24]
**Describe the bug**
If the time series passed to matrix profile is all zeroes or any constant, or a zero window-size is passed in, errors are raised which do not make the cause obvious.

**To Reproduce**
`profile, figures = mp.analyze(np.zeros(500))` -> `TypeError: 'float' object is not subscriptable`

```
dataset = mp.datasets.load('motifs-discords-small')
ts = dataset['data']
profile, figures = mp.analyze(ts, windows=[40, 0])
...
ValueError: could not broadcast input array from shape (876) into shape (875)
```

**Expected behavior**
The code raise a ValueError, or produce some output that is concordant with bad input.

**Comment by tylerwmarrs** [comment]
Thank you for pointing this out. We plan to integrate a fix soon.
