### ISSUE TITLE
Bug when calculating snippets with a small window size

### ISSUE THREAD

**Issue by DemianD** [matrix-profile-foundation/matrixprofile#27]
**Describe the bug**
When calculating snippets, an error is thrown

**To Reproduce**
```python
import matrixprofile as mp

snippet_size = 10
taxi = mp.datasets.load('nyc-taxi-anomalies')
ts = taxi['data']

snippets = mp.discover.snippets(ts, snippet_size, 2, snippet_size / 2)
```

**Expected behavior**

The snippets should be calculated correctly using all allowed snippet sizes

**Error log**

```
/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.7/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/usr/local/lib/python3.7/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/lib/python3.7/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[1]    42091 segmentation fault  python3 src/snippets/snippets-bug.py
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Python version: Python 3.7.3
- Matrixprofile version: 1.1.0

**Additional context**

The error is also raised with my own dataset where the snippet size is &le; 180.

**Comment by DemianD** [comment]
Second example with snippet size 201:

**To Reproduce**

```python
import matrixprofile as mp

snippet_size = 201
taxi = mp.datasets.load('nyc-taxi-anomalies')
ts = taxi['data']

snippets = mp.discover.snippets(ts, snippet_size, 2, snippet_size / 2)
```

**Error log**

```
Traceback (most recent call last):
  File "src/snippets/snippets-bug.py", line 7, in <module>
    snippets = mp.discover.snippets(ts, snippet_size, 2, snippet_size / 2)
  File "/usr/local/lib/python3.7/site-packages/matrixprofile/algorithms/snippets.py", line 73, in snippets
    distance = mpdist_vector(ts, ts[i:(i + snippet_size)], used_window)
  File "/usr/local/lib/python3.7/site-packages/matrixprofile/algorithms/mpdist.py", line 165, in mpdist_vector
    rows, cols = matrix.shape
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by tylerwmarrs** [comment]
@DemianD thank you for the bug report and examples. I am not sure how soon I can look into this issue. Are you willing to submit a pull request to fix this issue?

**Comment by DemianD** [comment]
I'm currently debugging why this is happening, but I'm not sure how to fix this.

https://github.com/matrix-profile-foundation/matrixprofile/blob/b71472e604c6337d1992651065dbe394b08b4ddc/matrixprofile/algorithms/mpdist.py#L100-L106

The `subseq_num` is sometimes zero or even negative, and thus nothing is added to the distances array. Calculating `np.array(distances)` of an empty array returns only one value instead of two. This is the reason why there are not enough values to unpack.

I probably need to focus more on why is zero `subseq_num` or even negative. 

https://github.com/matrix-profile-foundation/matrixprofile/blob/b71472e604c6337d1992651065dbe394b08b4ddc/matrixprofile/algorithms/mpdist.py#L100

Using my second example:

- `len(query)` = 201
- w = 202

Where does `w` come from?

It's calculated here: 

https://github.com/matrix-profile-foundation/matrixprofile/blob/b71472e604c6337d1992651065dbe394b08b4ddc/matrixprofile/algorithms/snippets.py#L62

I'm not sure what is happening here.

**Comment by tylerwmarrs** [comment]
@DemianD are you on our discord channel? I would like to have the ability to chat with you more directly. If you are, please send me a direct message.
