### ISSUE TITLE
Documentation - Snippets Tutorial

### ISSUE THREAD

**Issue by tylerwmarrs** [matrix-profile-foundation/matrixprofile#29]
Snippets algorithm exists in the library, but no example of how to use it exists in the documentation. The tutorial should cover the following:

1. High-level layman overview of a "snippet"
2. A practical use case (real-world data)

**Comment by Ninimama** [comment]
Hi Tyler,

Do you mean sth like what you did in 
[https://matrixprofile.docs.matrixprofile.org/Algorithms.html](url)
?

Just a brief explanation in simple words and using it on the same data to show the results?

Best,
Nima

**Comment by tylerwmarrs** [comment]
No. This issue was resolved through our website repository. https://matrixprofile.org/posts/what-are-time-series-snippets/
