### ISSUE TITLE
AttributeError: module 'matrixprofile' has no attribute 'datasets'

### ISSUE THREAD

**Issue by elopezfune** [matrix-profile-foundation/matrixprofile#33]
I installed matrixprofile a week ago and I am trying to reproduce the example in the documentation 
https://matrixprofile.docs.matrixprofile.org/examples/ECG_Annotation_Vectors.html
but as soon as I arrive to 

```
import matrixprofile as mp
import numpy as np

from matplotlib import pyplot as plt
%matplotlib inline

ecg = mp.datasets.load('ecg-heartbeat-av')
ts = ecg['data']
window_size = 150
```

I get the error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-93a2bc01725a> in <module>
      6 
      7 
----> 8 ecg = mp.datasets.load('ecg-heartbeat-av')
      9 ts = ecg['data']
     10 window_size = 150

AttributeError: module 'matrixprofile' has no attribute 'datasets'
```

I even tried mp.compute and I got the error

`AttributeError: module 'matrixprofile' has no attribute 'compute'`

Am I doing something wrong or are there missing packages or....?

**Comment by tylerwmarrs** [comment]
It appears that you are using a different library having the same namespace. What is the output of pip freeze?

**Comment by elopezfune** [comment]
The output is 
matrixprofile==1.1.2
matrixprofile-ts==0.0.9

**Comment by tylerwmarrs** [comment]
Yes, this is the problem. matrixprofile-ts has the same namespace and is more than likely the library being imported. Either create a new conda/virtual environment for matrixprofile or uninstall matrixprofile-ts. The latter library is no longer maintained.

**Comment by elopezfune** [comment]
I did but now it gives me another error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-65f024cc426b> in <module>
     10 ax.plot(np.arange(len(vals)),vals, label = 'Test Data')
     11 
---> 12 profile, figures = mp.analyze(vals)

AttributeError: module 'matrixprofile' has no attribute 'analyze'

**Comment by tylerwmarrs** [comment]
Please post the imports, pip freeze results, mp.__dict__ output, and mp.__version__ output.

**Comment by elopezfune** [comment]
I am reproducing the example in https://github.com/matrix-profile-foundation/article-matrix-profile-intro/blob/master/Matrix%20Profile%20Example.ipynb

**Comment by tylerwmarrs** [comment]
What about pip freeze? This still seems to be an environmental issue.

**Comment by elopezfune** [comment]
the pip freeze gives matrixprofile==1.1.2
pip freeze results gives the same matrixprofile==1.1.2

**Comment by tylerwmarrs** [comment]
Please try the following:

1. create a virtual environment

```
# via conda
conda create --name mptest

# via virtualenv
virtualenv mptest
```

2. activate the environment

```
# via conda
conda activate mptest

# via virtualenv (may be different for Windows)
source mptest/bin/activate
```

3. install matrixprofile

```
pip install matrixprofile
```

4. run this script within your virtual environment
```
import matrixprofile as mp
import numpy as np

ts = np.arange(100)
profile, figures = mp.analyze(ts)
```

You should not receive any errors when going through these steps unless there is some larger environmental issue. Maybe one issue is that your notebook does not have the same environment as you expect?

**Comment by elopezfune** [comment]
Well, I tried your procedure and I am still getting

(mptest) elopezfune@elopezfune:~$ python3 '/home/elopezfune/Téléchargements/legend.py'
Traceback (most recent call last):
  File "/home/elopezfune/Téléchargements/legend.py", line 5, in <module>
    profile, figures = mp.analyze(ts)
AttributeError: module 'matrixprofile' has no attribute 'analyze'

**Comment by vanbenschoten** [comment]
I'd recommend un-installing matrixprofile-ts, as it's probably a namespace
collision between packages.

**Comment by tylerwmarrs** [comment]
@elopezfune do you have any further updates on this issue? It may be easier to debug in our Discord chat. You can find a link within the code repository Readme

**Comment by elopezfune** [comment]
I am re-installing everything from the beginning

**Comment by elopezfune** [comment]
So, I uninstalled matrixprofile and re-installed everything from the beginning. Now ModuleNotFoundError: No module named 'matrixprofile' when importing
I think I will look for other alternatives to Motif discovery
Thanks for the help anyways!

**Comment by tylerwmarrs** [comment]
Thank you for the update. Good luck.
