### ISSUE TITLE
minor change?

### ISSUE THREAD

**Issue by Ninimama** [matrix-profile-foundation/matrixprofile#45]
Hi,

After a long delay, working on my paper and studying git, I pulled and realized  Yue Lu had already modified the snippet algorithm. 

As I was reviewing the code, I realized that he added a new key "neighbors" to the snippet dictionary; however, the docstring wasn't updated accordingly. 

**If I find some small issues like that again, should I mention here or modify it (since I already have it on my local pc) and do merge request?** 

Thanks,
Nima

**Comment by tylerwmarrs** [comment]
Any code changes you want to make can be submitted via pull request.

**Comment by Ninimama** [comment]
Hi, I did the pull request for updating docstring, but I now see LuYueee already addressed this issue as well.
