### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by Bruno-Hanzen** [matrix-profile-foundation/matrixprofile#58]
**Describe the bug**
n_jobs argument not passed to "maximum_subsequence" and "skimp" in "Analyze_pmp"

**To Reproduce**
1. call mp.analyze with a time series and an n_jobs value with different n_jobs values
2. monitor cpu utilization on a multi-core system
3. whatever the n_jobs value, the task uses a single core, and execution time is the same

**Expected behavior**
1. if n_jobs >1, several cores are used
2. n_jobs has an impact on execution time

**Root cause**
n_jobs argument not passed to "maximum_subsequence" and "skimp" in "Analyze_pmp"

**Solution**

add "n_jobs=n_jobs" in the calls:
`if isinstance(windows, type(None)):` 
`         profile = maximum_subsequence(ts, threshold, include_pmp=True, n_jobs=n_jobs)`

`    profile = skimp(ts, windows=windows, sample_pct=sample_pct, \n`
`                          pmp_obj=profile, n_jobs=n_jobs)`

**Result**
For the same series, on the same computer:
Execution time of "mp.analyze"
n_jobs = 12: 1158.7 s.
n_jobs = 8: 1068.4 s.
n_jobs = 4: 1069.6 s.
n_jobs = 1: 1632.3 s

**Comment by tylerwmarrs** [comment]
Thank you for reporting the issue. Do you intend to submit a pull request? If not, I will try to dig into this either today or tomorrow.

Keep in mind that with multithreading there is an upper bound where it actually hurts performance. It is relatable to the "too many cooks in the kitchen."

**Comment by Bruno-Hanzen** [comment]
Pull request submitted.
In French, we say "Trop de cuisiniers gâchent la sauce" - Too many cooks spoil the broth
