### ISSUE TITLE
Python 3.9 Binary Wheels for Linux and MacOS

### ISSUE THREAD

**Issue by tylerwmarrs** [matrix-profile-foundation/matrixprofile#68]
Our wheel build system is reliant on the package cibuildwheel. Currently, our TravisCI script has some environment issues with Python and pulling down the required version of cibuildwheel for Python 3.9 support. The version required for cibuildwheel to build wheels on Python 3.9 is v1.6.2.

See these logs for Linux and MacOS issues:

https://travis-ci.com/github/matrix-profile-foundation/matrixprofile/jobs/464939617
https://travis-ci.com/github/matrix-profile-foundation/matrixprofile/jobs/464939618

Windows is successfully building wheel for Python 3.9.

**Comment by tylerwmarrs** [comment]
This is fixed for Linux. I need a MacOS user to assist with the appropriate commands to install Python 3.8. @vanbenschoten are you able to assist here or @frankiecancino ?

Basically, I need to know how to get this to work:

```
brew install python@3.8                                                 
brew upgrade python@3.8                                                 
brew link --force python@3.8 
```

My readings online show that this should install Python 3.8 and link it as the default. Can one of you test and let me know the result?

**Comment by vanbenschoten** [comment]
@frankiecancino can you help here? I don't have a Mac any more.

**Comment by frankiecancino** [comment]
For which Python version? @tylerwmarrs you mentioned issues with Python 3.9 in the first comment, but Python 3.8 in the second comment.

**Comment by tylerwmarrs** [comment]
3.8 is a baseline version for cibuildwheel, a package used for building
binary python wheels, to be able to build version 3.9 binary wheels of
matrixprofile. You can use 3.8 or 3.9 to provide feedback. Please look at
the latest commits to the TravisCI for some clarity if needed.

**Comment by jacksongreen28** [comment]
I was able to successfully get python 3.8 working using the commands above except for the final one. Here is the command I used:
```
brew link --overwrite python@3.8
```
This should create the symlinks

**Comment by tylerwmarrs** [comment]
This is still an issue. I cannot seem to resolve it. The issue that I'm having is that when I try to make Python 3.8 as the default python version, cibuildwheel still tries to use Python 2.7 making it not work with the required version of cibuildwheel for building Python 3.9.

**Comment by tylerwmarrs** [comment]
MacOSx is now building successfully against Python 3.5 to 3.9!!!!!!!
