### ISSUE TITLE
Updated matrix profile codebase

### ISSUE THREAD

**Issue by vanbenschoten** [matrix-profile-foundation/matrixprofile#7]
@ltbd78 @nikita-smyrnov MPF has released the latest Matrix Profile codebase under our own GitHub repo. The issues you raised regarding nan values and non-functional annotation vectors have been resolved.

**Comment by nikita-smyrnov** [comment]
@vanbenschoten I think the annotation vectors still haven't been added in? I was looking through the codebase and couldn't find any reference to them. Could you point me to the specific file(s) where they are mentioned? Thanks!

**Comment by tylerwmarrs** [comment]
@nikita-smyrnov Annotation vectors are not implemented right now. Please see issue #11. I would love to get your feedback.
