### ISSUE TITLE
Strict dependency on protobuf 3.11.2

### ISSUE THREAD

**Issue by burk** [matrix-profile-foundation/matrixprofile#75]
**Describe the bug**

There still seems to be a strict dependency on protobuf 3.11.2, even though this commit seems to try to remove that strict version dependency: https://github.com/matrix-profile-foundation/matrixprofile/commit/37173af1904e761bda509de41cd4cfbeacf23fcd

I'm not able to lock the version of matrixprofile inside a pipenv with another library which requires protobuf >= 3.12.0

**To Reproduce**
1. Download the latest Python 3.8 matrixprofile linux wheel.
2. Unzip it.
3. Look inside the file `matrixprofile-1.1.10.dist-info/METADATA`
4. Observe the line `Requires-Dist: protobuf (==3.11.2)`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Version: Python 3.8, matrixprofile 1.110

**Comment by burk** [comment]
I've identified the problem: https://github.com/matrix-profile-foundation/matrixprofile/pull/76

**Comment by vanbenschoten** [comment]
@burk Thanks for the PR! Apologies as I've been a little delayed - I'll look at the change shortly.

**Comment by vanbenschoten** [comment]
Corresponding PR approved and merged. Thanks!

**Comment by alexvorobiev** [comment]
Pypi version still has this restriction.
