### ISSUE TITLE
Threshold

### ISSUE THREAD

**Issue by TinaShi** [matrix-profile-foundation/matrixprofile#78]
When I use mp.compute or mp.analyze, I get the error "NoSolutionPossible: Given the threshold {:.2f}, no window was found. Please try increasing your threshold." How do I adjust it?

**Comment by vanbenschoten** [comment]
@TinaShi I assume you're using the pan-Matrix Profile (aka not specifying a specific window size)? If that's the case then you'll need to change the compute parameter to something lower than the default value of 0.98 per the documentation: https://matrixprofile.docs.matrixprofile.org/api.html#matrixprofile-compute.

Feel free to re-open if you still think there's an issue here.
