### ISSUE TITLE
The paper of mpx

### ISSUE THREAD

**Issue by RexKing6** [matrix-profile-foundation/matrixprofile#79]
Can someone share the paper of mpx? 

I can't find the related papers. 

Thank you!!!

**Comment by vanbenschoten** [comment]
@RexKing6 IIRC there's no official MPX paper - it's an implementation approach that's baked into the MATLAB code from Eamonn's lab. @franzbischoff might be able to tell you more.

**Comment by franzbischoff** [comment]
@RexKing6, like @vanbenschoten said, there is no published paper about it. Don't ask me why...
You can take a look at my last benchmarks here: https://rpubs.com/franzbischoff/matrixprofiler
mpx turns out to be the fastest and is also anytime. There is no "online" version (yet) though.

**Comment by RexKing6** [comment]
Thank you very much! I am going to learn its specific process from this benchmark test and the source code of mpx.

**Comment by vanbenschoten** [comment]
@RexKing6 I'd also recommend e-mailing Eamonn Keogh directly as he's usually more than happy to discuss the algorithms in greater depth.
