### ISSUE TITLE
The website (https://matrixprofile.org/) is down.

### ISSUE THREAD

**Issue by wendeldr** [matrix-profile-foundation/matrixprofile#83]
Hi

I didn't know where else to contact your group, it seems like your https://matrixprofile.org/ website is offline.  Just thought I'd let you guys know incase you didn't see it.

**Comment by vanbenschoten** [comment]
Thanks @wendeldr! We're aware of the situation and actively working towards a resolution. Thanks for the heads up!

**Comment by vanbenschoten** [comment]
Update: the website issue has been resolved and should be live in ~20 minutes. Thank you!
