### ISSUE TITLE
pip install matrixprofile forces protobuf==3.11.2

### ISSUE THREAD

**Issue by carlydf** [matrix-profile-foundation/matrixprofile#84]
**Describe the bug**
We need protobuf > 3.11.2 for other dependencies.

**To Reproduce**
1. pip install matrixprofile
2. pip install --upgrade protobuf 
Should install protobuf v3.17.3 which it does. It also errors saying `matrixprofile 1.1.10 requires protobuf==3.11.2, but you have protobuf 3.17.3 which is incompatible.` despite the fact that `matrixprofile/requirements.txt` in v1.1.10 says `protobuf>=3.11.2,<4.0.0`
3. pip install matrixprofile
This uninstalls protobuf and installs protobuf==3.11.2, which is the wrong behavior

**Expected behavior**
I expect protobuf to be left alone, since the stated requirements for matrixprofile is just `protobuf>=3.11.2,<4.0.0`

**Additional context**
I believe the problem is that `matrixprofile/setup.py` required `protobuf==3.11.2` until March 8, 2021, and the latest release was released on January 16, 2021. I think the bug would be fixed by creating another release.

pip installing matrixprofile from [the commit where setup.py relaxed the protobuf version requirement](https://github.com/matrix-profile-foundation/matrixprofile/commit/e05b0493f467c925f79c0c5e298ce389dacca175) resolves the issue

**Comment by vanbenschoten** [comment]
Hi @carlydf, thanks for letting me know! I'll look into it shortly.

**Comment by pedro-ricardo** [comment]
Hello there, 

I'm currently with the same problem. Despite the `requirements.txt` shows a clear `protobuf>=3.11.2,<4.0.0` the pip install print out this error: `protobuf==3.11.2 (from matrixprofile==1.1.10` . . .

This happens because I have another dependency that needs `protobuf>=3.12.0`

### How to replicate:
- `$ python3 -m venv .venv`
- `$ source .venv/bin/activate`
- `$ pip3 install matrixprofile protobuf>=3.12.0`
- Error is: `matrixprofile 1.1.10 requires protobuf==3.11.2`

**Comment by pedro-ricardo** [comment]
@vanbenschoten do you have an estimate to have this looked into?

**Comment by vanbenschoten** [comment]
@pedro-ricardo not at the moment, though hopefully soon. If you'd like to create a PR I can also review :)

**Comment by pedro-ricardo** [comment]
Thank you for the feedback. We'll find a workaround. :+1:

**Comment by peterdhansen** [comment]
>I think the bug would be fixed by creating another release.

in the original issue, @carlydf pointed out the fix is already implemented, but no release has been published

for now `pip install git+ssh://git@github.com:matrix-profile-foundation/matrixprofile.git` will get you the github version with the correct requirements.txt

**Comment by pedro-ricardo** [comment]
Installing through pip does solve the install issue.

But some dependency resolver, like the ones from Kedro, start to have bugs with this .. like:
```
ERROR: Cannot install matrixprofile 1.1.10 (from git+git://github.com/matrix-profile-foundation/matrixprofile@6bea7d4445) because these package versions have conflicting dependencies
The conflict is caused by:
    The user requested matrixprofile 1.1.10 (from git+git://github.com/matrix-profile-foundation/matrixprofile@6bea7d4445)
    my-package 1.1.0 depends on matrixprofile 1.1.10 (from git+https://github.com/matrix-profile-foundation/matrixprofile.git@6bea7d4445)
```
This does not make sense at all .. and it is not your problem ...

But how far are we from releasing the master branch as `1.1.11` ?

**Comment by theoohoho** [comment]
Got same issue on install `v1.1.10`. It would be really helpful if release a patch. 🙏

**Comment by uabbas** [comment]
> Got same issue on install `v1.1.10`. It would be really helpful if release a patch. 🙏

I would second this. A  release would be great.

**Comment by RouvenG** [comment]
I would also be happy about a release!

**Comment by eliorc** [comment]
Still a problem

**Comment by harryrose94** [comment]
Would also be happy for a release please.

I am not trying to pip install matrixprofile, but rather I am using a package which has a dependency on matrixprofile. Either way the same problem occurs.

I have been able to resolve the protobuf==3.11.2 conflict by including the below in my personal projects setup.py file. 

`install_requires=["matrixprofile @ git+https://git@github.com/matrix-profile-foundation/matrixprofile.git"]`

Hopefully this can help anyone with the same issue.

**Comment by gchlebus** [comment]
Would also be happy for a patch release please.

**Comment by tim-habitat** [comment]
A patch release would be amazing! A few downstream libraries depend on you guys and `protobuf` seem to be used quite a bit so conflicts arise often.

**Comment by ekamperi** [comment]
Hey everyone! Any roadmap on this one? I just hit it myself. Thanks! Let me know if I could help somehow in testing!

**Comment by jackalack** [comment]
Also an issue for us. Has anyone found a workaround?

**Comment by jcoffi** [comment]
Can confirm, the issue still exists. Is this software even being actively managed anymore?

**Comment by vanbenschoten** [comment]
This library is no longer actively maintained. We recommend using the STUMPY library moving forward: https://github.com/TDAmeritrade/stumpy
