### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by lmmentel** [matrix-profile-foundation/matrixprofile#91]
**Is your feature request related to a problem? Please describe.**
It would be great it `matrixprofile` could support python 3.10.

**Describe the solution you'd like**
It would be great it `matrixprofile` could support python 3.10.

**Describe alternatives you've considered**

**Additional context**

Although I can install `matrixprofile==1.1.10` with python 3.10 on linux, when I try to import I get an error about circular import

```
❯ python
Python 3.10.1 (main, Jan  2 2022, 14:37:42) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matrixprofile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/projects/matrixprofile/matrixprofile/__init__.py", line 8, in <module>
    from matrixprofile.compute import compute
  File "/home/test/projects/matrixprofile/matrixprofile/compute.py", line 20, in <module>
    from matrixprofile import core
  File "/home/test/projects/matrixprofile/matrixprofile/core.py", line 17, in <module>
    from matrixprofile import cycore
ImportError: cannot import name 'cycore' from partially initialized module 'matrixprofile' (most likely due to a circular import) (/home/test/projects/matrixprofile/matrixprofile/__init__.py)
>>> 
```

**Comment by tomasApo** [comment]
Any traction on support for 3.10?

**Comment by jonasvdd** [comment]
🙏🏼

**Comment by CyrilLeMat** [comment]
I really need a 3.10 support if I want my project to continue using matrixprofile.
Is there absolutely no plan for such a support?

**Comment by vanbenschoten** [comment]
This library is not supported moving forward. We recommend using the STUMPY library instead, which is able to replace all functionality in this package (https://github.com/TDAmeritrade/stumpy)
